#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print("Zagrajmy w grę! Podaj trzy liczby całkowite")

x=input("Podaj pierwszą liczbę ")
y=input("Podaj drugą liczbę ")
z=input("Podaj trzecią liczbę ")

wynik = int(x)+int(y)+int(z)

iloczyn = int(x)*int(y)*int(z)

kwadrat_x = int(x)*int(x)
kwadrat_y = int(y)*int(y)
kwadrat_z = int(z)*int(z)

kwadraty = int(kwadrat_x) + int(kwadrat_y) + int(kwadrat_z)

print("Suma wynosi: ", wynik)

print("Iloczyn wynosi: ", iloczyn)

print("Suma kwadratów wynosi: ", kwadraty)

#Piotr Zandecki
