#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import random

liczba = random.randint(1, 10)

for i in range(3):
    print("Próba ", i + 1)
    odp = input("Jaką liczbę od 1 do 10 mam na myśli? ")
    if liczba == int(odp):
        print("OK. Gratuluję")
        break
    elif liczba > int(odp):
        print("za mało")
    elif liczba < int(odp):
        print("za dużo")

        # Piotr Zandecki
