#!/usr/bin/env python3
# -*- coding: utf-8 -*-

n=input("Podaj liczbę ")
n=int(n)

def fibo(n):
    if (n == 0):
        return 0
    if (n == 1):
        return 1
    return fibo(n-1)+fibo(n-2)

print(fibo) #nie wiem jak wydrukować wynik tej funkcji

#Piotr Zandecki
